# OB-1 Enhanced Multi-Engine Configuration
# Production setup for IO.NET deployment

ai_engines:
  ob1:
    enabled: true
    priority: 1
    capabilities:
      - text_analysis
      - blockchain_analysis
      - defi_analysis
      - security_analysis
    
  copilot:
    enabled: true
    priority: 2
    capabilities:
      - code_suggestions
      - code_explanation
      - cli_integration
    
  r2d2:
    enabled: false
    priority: 3
    capabilities:
      - multi_modal_analysis
      - advanced_reasoning
      - coming_soon

server:
  host: "0.0.0.0"
  port: 5000
  debug: false
  workers: 2
  timeout: 120

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/ob1-agent.log"

security:
  cors_enabled: true
  rate_limiting: true
  max_requests_per_minute: 60

github:
  webhook_secret: "${GITHUB_WEBHOOK_SECRET}"
  token: "${GITHUB_TOKEN}"
  auto_analysis: true

ionet:
  deployment_target: container_engine
  compute_requirements:
    cpu_cores: 2
    memory_gb: 4
    storage_gb: 10
  health_check_path: "/health"
  readiness_probe: "/health"
  liveness_probe: "/health"